VNS.Web/Models/Home/VisitViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace VNS.Web.Models.Home
{
    public class VisitViewModel
    {
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyy}")]
        public DateTime Date { get; set; }

        public string NurseName { get; set; }

        public string Description { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyy HH:mm}")]
        public DateTime CreatedOn { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyy HH:mm}")]
        public DateTime LastModifiedOn { get; set; }
    }
}

VNS.Web/Models/Visits/MunicipalityViewModel.cs
using System.Collections.Generic;

namespace VNS.Web.Models.Visits
{
    public class MunicipalityViewModel
    {
        public string Name { get; set; }

        public ICollection<string> Towns { get; set; }
    }
}

VNS.Web/Models/Visits/SearchViewModel.cs
using System.Collections.Generic;

namespace VNS.Web.Models.Visits
{
    public class SearchViewModel
    {
        public ICollection<MunicipalityViewModel> Municipalities { get; set; }
    }
}

VNS.Web/Models/Visits/VisitCardViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using VNS.Data.Models;

namespace VNS.Web.Models.Visits
{
    public class VisitCardViewModel
    {
        private readonly int descriptionMaxLen = 200;
        private string description;

        public VisitCardViewModel()
        {

        }

        public VisitCardViewModel(Visit visit)
        {
            this.Id = visit.Id;
            this.Date = visit.Date;
            this.NurseName = visit.UserName;
            this.Description = visit.Description;
        }

        public Guid Id { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yy}")]
        public DateTime Date { get; set; }

        public string NurseName { get; set; }

        public string Description
        {
            get
            {
                return this.description;
            }
            set
            {
                this.description = value.Length > this.descriptionMaxLen
                    ? value.Substring(0, this.descriptionMaxLen) + "..."
                    : value;
            }
        }
    }
}

VNS.Web/Models/Visits/VisitDetailsViewModel.cs
using Bytes2you.Validation;
using System;
using System.ComponentModel.DataAnnotations;
using VNS.Data.Models;
using VNS.Data.Models.ValidationRules;
using Rules = VNS.Data.Models.ValidationRules.PropertiesConstraints;

namespace VNS.Web.Models.Visits
{
    public class VisitDetailsViewModel
    {
        //private readonly int descriptionMaxLen = 200;
        //private string description;

        public VisitDetailsViewModel()
        {

        }

        public VisitDetailsViewModel(Visit visit)
        {
            Guard.WhenArgument(visit, "visit").IsNull().Throw();

            Id = visit.Id;
            Date = visit.Date;
            NurseName = visit.UserName;
            Description = visit.Description;
            CreatedOn = visit.CreatedOn; //.Value,
            LastModifiedOn = visit.ModifiedOn;//.Value
        }


        public Guid Id { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [PastDate]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        [Display(Name = "Nurse name")]
        public string NurseName { get; set; }


        [Required(ErrorMessage = "This field is required")]
        [StringLength(Rules.DescriptionMaxLength, ErrorMessage = Rules.StringLengthError, MinimumLength = Rules.DescriptionMinLength)]
        public string Description { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yy HH:mm}")]
        public DateTime CreatedOn { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yy HH:mm}")]
        public DateTime? LastModifiedOn { get; set; }

        // TODO: add other fields
        // TODO: extract validation messages??
    }
}

VNS.Web/Models/Visits/VisitsViewModel.cs
using System.Collections.Generic;

namespace VNS.Web.Models.Visits
{
    public class VisitsViewModel
    {
        // TODO: should collections in view models be init in ctor??

        public IEnumerable<VisitCardViewModel> Visits { get; set; }

        public int PageCount { get; set; }
    }
}

VNS.Web/Controllers/VisitsController.cs
using Bytes2you.Validation;
using System;
using System.Collections;
using System.Linq;
using System.Web.Mvc;
using VNS.Auth.Contracts;
using VNS.Data.Models;
using VNS.Services.Contracts;
using VNS.Web.Models.Visits;
using static VNS.Web.Helpers.HtmlHelpers;

namespace VNS.Web.Controllers
{
    public class VisitsController : Controller
    {

        private readonly IMunicipalitiesService municipalitiesService;
        private readonly IVisitsService visitsService;
        private readonly IUserService usersService;
        private readonly IPageService<Visit> pageService;

        public VisitsController(IVisitsService visitsService, IMunicipalitiesService municipalitiesService, IUserService usersService, IPageService<Visit> pageService)
        {
            Guard.WhenArgument(visitsService, "visitsService").IsNull().Throw();
            Guard.WhenArgument(municipalitiesService, "municipalitiesService").IsNull().Throw();
            Guard.WhenArgument(usersService, "usersService").IsNull().Throw();
            this.visitsService = visitsService;
            this.municipalitiesService = municipalitiesService;
            this.usersService = usersService;
            this.pageService = pageService;
        }

        public ActionResult Index(short page = 1, short pageSize = 9, string orderBy = "CreatedOn")
        {
            // TODO: add period filtering
            var munis = this.municipalitiesService
                .GetAll()
                .Select(m => new MunicipalityViewModel()
                {
                    Name = m.Name,
                    Towns = m.Towns.Select(t => t.Name).ToList()
                })
                .ToList();

            var viewModel = new SearchViewModel()
            {
                Municipalities = munis,             
            };

            return View(viewModel);
        }

		// TODO : consider adding ajaxOnly check
        //[AjaxOnly]
        public ActionResult Open(Guid id)
        {
            // TODO: Consider another way to stop non-ajax requests
            // without reloading page - AjaxOnly attribute but with some feedback
            // TODO: uncomment when dev finished, add to ather ajax methods
            //if (!this.Request.IsAjaxRequest())
            //{
            //    TempData["message"] = "Not an ajax request";
            //    return RedirectToAction("Index");
            //}

            // TODO: remove
            //var test3 = Request;
            //var test = Request.Url.Query;
            //var test2 = Request.QueryString["name"];

            var visit = this.visitsService.GetById(id);

            VisitDetailsViewModel vm = new VisitDetailsViewModel(visit);

            return PartialView("_VisitDetailsPartial", vm);
        }

        // TODO: Fix redirect not working for not logged user
        //[HttpGet]
        [Authorize]
        public ActionResult Edit(Guid id)
        {
            // TODO: Check for null
            var visit = this.visitsService.GetById(id);
            var vm = new VisitDetailsViewModel(visit);

            return PartialView("_VisitEditPartial", vm);
        }

        // TODO: Add to all post actions
        //[ValidateAntiForgeryToken]
        //[Authorize]
        [HttpPost]
        public ActionResult Edit(VisitDetailsViewModel visit)
        {
            // if view model not valid
            if (!ModelState.IsValid)
            {
                return PartialView("_VisitEditPartial", visit);
            }

            // find the visit to edit from database
            var v = this.visitsService.GetById(visit.Id);

            // update
            v.Date = visit.Date;
            v.Description = visit.Description;
            this.visitsService.Update(v);

            // cheat
            visit.LastModifiedOn = DateTime.Now;

            return PartialView("_VisitDetailsPartial", visit);
        }


        [Authorize]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        //[ValidateAntiForgeryToken]
        public ActionResult Add(VisitDetailsViewModel visit)
        {
            if (!ModelState.IsValid)
            {
                return View(visit);
            }

            var v = new Visit()
            {
                Date = visit.Date,
                Description = visit.Description,
                UserName = visit.NurseName
            };

            this.visitsService.Add(v);

            // TODO: review - add success message, redirect??
            TempData["message"] = "Visit added successfully";
            return Redirect("Index");
        }

        public ActionResult List(short page = 1, short pageSize = 6, string orderBy = "CreatedOn")
        {
            var pagedVisits = this.pageService
                .GetPage(page, pageSize, orderBy)
                .Select(v => new VisitCardViewModel(v));

            var pages = this.pageService.Count / pageSize;
            pages = this.pageService.Count % pageSize == 0 ? pages : ++pages;
            
            var vm = new VisitsViewModel()
            {
                Visits = pagedVisits,
                PageCount = pages
            };

            return PartialView("_VisitsListPartial", vm);
        }
    }
}

VNS.Web/Views/Visits/Add.cshtml
@using VNS.Web.Models.Visits
@model VisitDetailsViewModel

<p>Add new visit form</p>


@using (Html.BeginForm("Add", "Visits", FormMethod.Post, new { @class = "small" }))
{
    @*@Html.AntiForgeryToken()*@

    <fieldset>
        <div class="form-group">
            @Html.LabelFor(v => v.Date, new { @class = "control-label" })
            @Html.EditorFor(v => v.Date, new { htmlAttributes = new { @class = "form-control input-sm" } })
            @Html.ValidationMessageFor(v => v.Date, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(v => v.NurseName, new { @class = "control-label" })
            @* TODO: Admins should be able to add visits for other users *@
            <input class="form-control input-sm" name="NurseName" value=@Context.User.Identity.Name readonly="readonly"/>
            @*@Html.TextBoxFor(v => Context.User.Identity.Name, new  { @class = "form-control input-sm", name="NurseName", @readonly = "true" })*@
        </div>
        <div class="form-group">
            @Html.LabelFor(v => v.Description, new { @class = "control-label" })
            @Html.EditorFor(v => v.Description, new { htmlAttributes = new { @class = "form-control input-sm" } })
            @Html.ValidationMessageFor(v => v.Description, "", new { @class = "text-danger" })
        </div>


    </fieldset>
    <div class="clearfix">
        @Html.ActionLink("Cancel", "Index", null, new { @class= "btn btn-default btn-sm"})
        <button type="submit" class="btn btn-warning btn-sm">Save</button>
        @*<p class="edit-info pull-right">
            Added: @Html.DisplayFor(v => Model.CreatedOn)<br />
            Edited: @Html.DisplayFor(v => Model.LastModifiedOn)
        </p>*@
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VNS.Web/Views/Visits/Edit.cshtml
@using VNS.Web.Models.Visits
@model VisitDetailsViewModel

<p>Edit form</p>

@using (Html.BeginForm("Edit", "Visits", FormMethod.Post, new { @class = "small" }))
{
    @*@Html.AntiForgeryToken()*@
    
    <fieldset>
        @* TODO: How controller recieves id even without this field *@
        @Html.HiddenFor(v => v.Id)

        <div class="form-group">
            @Html.LabelFor(v => v.Date, new { @class = "control-label" })
            @Html.EditorFor(v => v.Date, new { htmlAttributes = new { @class = "form-control input-sm" } })
            @Html.ValidationMessageFor(v => v.Date)
        </div>
        <div class="form-group">
            @Html.LabelFor(v => v.NurseName, new { @class = "control-label" })
            @Html.EditorFor(v => v.NurseName, new { htmlAttributes = new { @class = "form-control input-sm", @readonly = "true" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(v => v.Description, new { @class = "control-label" })
            @Html.EditorFor(v => v.Description, new { htmlAttributes = new { @class = "form-control input-sm" } })
            @Html.ValidationMessageFor(v => v.Description, "", new { @class = "text-danger" })
        </div>


    </fieldset>
    <div class="clearfix">
        <button type="submit" class="btn btn-warning btn-sm pull-left">Save</button>
        <p class="edit-info pull-right">
            Added: @Html.DisplayFor(v => Model.CreatedOn)<br />
            @Html.HiddenFor(v => Model.CreatedOn)
            Edited: @Html.DisplayFor(v => Model.LastModifiedOn)
            @Html.HiddenFor(v => Model.LastModifiedOn)
        </p>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VNS.Web/Views/Visits/Form.cshtml
@using VNS.Web.Models.Visits
@model VisitDetailsViewModel

<p>Edit form</p>


@using (Html.BeginForm("Form", "Visits", FormMethod.Post, new { @class = "small" }))
{
    @*@Html.AntiForgeryToken()*@

    @*@Html.EditorForModel()*@
    <fieldset>
        <div class="form-group">
            @Html.LabelFor(v => v.Date, new { @class = "control-label" })
            @Html.EditorFor(v => v.Date, new { htmlAttributes = new { @class = "form-control input-sm" } })
            @Html.ValidationMessageFor(v => v.Date)
        </div>
        <div class="form-group">
            @Html.LabelFor(v => v.NurseName, new { @class = "control-label" })
            @Html.DisplayFor(v => v.NurseName, new { @class = "control-label" })
            @Html.EditorFor(v => v.NurseName, new { htmlAttributes = new { @class = "form-control input-sm", disabled = "true" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(v => v.Description, new { @class = "control-label" })
            @Html.EditorFor(v => v.Description, new { htmlAttributes = new { @class = "form-control input-sm" } })
            @Html.ValidationMessageFor(v => v.Description, "", new { @class = "text-danger" })
        </div>


    </fieldset>
    <div class="clearfix">
        <button type="submit" class="btn btn-warning btn-sm pull-left">Save</button>
        <p class="edit-info pull-right">
            Added: @Html.DisplayFor(v => Model.CreatedOn)<br />
            Edited: @Html.DisplayFor(v => Model.LastModifiedOn)
        </p>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VNS.Web/Views/Visits/Index.cshtml
@using VNS.Web.Models.Visits
@model SearchViewModel
@{
    ViewBag.Title = "Visits";
    ViewBag.Message = "Information about work with families";
}

<header class="row">
    <div class="col-md-12 text-center">
        <h2>@ViewBag.Title.</h2>
        <p>@ViewBag.Message</p>

        @if (TempData["message"] != null)
        {
            <div id="msg" class="vns-message alert alert-dismissible alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                @TempData["message"] (TempData)
            </div>
        }

    </div>
</header>

<section id="vns-search" class="row">
    <div class="col-sm-3 col-xs-5">
        <img src="~/Content/images/baby-25.svg" alt="duck" class="page-image" />
    </div>
    <div class="col-sm-9 col-xs-12">
        @Html.Partial("_SearchPartial", Model)
    </div>
</section>

<hr />

<section id="vns-cards-content" class="row">

    @Html.Action("List")
    
</section>

@* Modal wrapper *@

<div id="vns-visit-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" id="vns-modal-content">
        <div class="modal-content">
            <div class="modal-body text-center">
                <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                <span class="sr-only">Loading...</span>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    @* TODO: don't forget to include in other pages using ajax*@
    @* Validates data before form submission *@
    @Scripts.Render("~/bundles/jqueryajax")
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        // Hides TempData message
        $('#msg').delay(3000).fadeOut(300);

        // Clears the content of the modal when closed
        $('#vns-visit-modal').on('hidden.bs.modal', function () {
            $('#vns-modal-content').html('<div class="modal-content"><div class="modal-body text-center"><i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i><span class="sr-only">Loading...</span></div></div>');
        })
    </script>

    @* TODO: remove *@
    @* Script to load visit card details when using regular anchor tag
        instead of  ajax.actionlink *@
    @*<script>
            function showModal() {
                $('#vns-visit-modal').modal('show');
            }
            $('#btnOpen').click(function (eve) {
                $('#vns-modal-content').load("/Visits/Open?name=" + $(this).data("name"));
            })

            $('#btnEdit').click(function (eve) {
                $('#vns-modal-content').load("/Visits/Edit?name=" + $(this).data("name"));
            })
        </script>*@
}

VNS.Web/Views/Visits/_SearchPartial.cshtml
@using VNS.Web.Models.Visits
@model SearchViewModel

@*
TODO: extract to partial view, to be able to use for families too
TODO: Filter based on selected muni
    <h3>Select criteria</h3>
<p>Municipality, Town, Family ref#, Nurse</p>

@using (Html.BeginForm("Action", "Controller", FormMethod.Get, new { id = "searchVisitsForm", @class = "", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-sm-3">
            <div class="form-group">
                <label for="municipality">Municipality</label><br />
                <select class="dropdown" name="municipality">
                    <option>- All -</option>
                    @foreach (var muni in Model.Municipalities)
                    {
                        <option value=@muni.Name.ToLower()> @muni.Name </option>
                    }
                </select>
            </div>
        </div>

        <div class="col-sm-3">
            <div class="form-group">
                <label for="towns">Town</label><br />
                <select class="dropdown" name="towns">
                    <option>- All -</option>
                    
                    @foreach (var muni in Model.Municipalities)
                    {
                        foreach (var town in muni.Towns)
                        {
                            <option value=@town.ToLower()> @town </option>
                        }
                    }
                </select>
            </div>
        </div>
    </div>
    }*@

    <div class="row">
        @*<button type="reset" class="btn btn-default btn-sm">Clear</button>*@
        @*<button type="submit" class="btn btn-success btn-sm">Search</button>*@
        @Html.ActionLink("Add", "Add", "Visits", null, new { @class = "btn btn-info btn-sm" })
    </div>

VNS.Web/Views/Visits/_VisitCardPartial.cshtml
@using VNS.Web.Models.Visits
@model VisitCardViewModel

<article class="col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            @*<button type="button" class="btn btn-warning btn-sm btn-circle">
                    <i class="fa fa-pencil"></i>
                </button>*@
            <img src="~/Content/images/girl-01.svg" class="profile-image pull-right" alt="profile-image" />
            <h4>@Model.NurseName</h4>
            <p>@Model.Date.ToString("dd.MM.yy")</p>
        </div>
        <div class="panel-body">
            <p>@Model.Description</p>
        </div>
        <div class="panel-footer">
            @Ajax.ActionLink("Open", "Open", "Visits",
                new { Id = Model.Id },
                new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "vns-modal-content" },
                new { @class = "btn btn-success btn-sm", data_toggle = "modal", data_target = "#vns-visit-modal" })

            @Ajax.ActionLink("Edit", "Edit", "Visits",
                new { Id = Model.Id },
                new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "vns-modal-content" },
                new { @class = "btn btn-warning btn-sm", data_toggle = "modal", data_target = "#vns-visit-modal" })

        </div>
    </div>
</article>

VNS.Web/Views/Visits/_VisitDetailsPartial.cshtml
@using VNS.Web.Models.Visits
@model VisitDetailsViewModel

<div class="modal-content">
    <div class="modal-header">
        <img src="~/Content/images/girl-01.svg" class="profile-image pull-right" alt="profile-image" />
        <h4>@Model.NurseName</h4>
        <p>@Model.Date.ToString("dd.MM.yy")</p>

    </div>
    <div class="modal-body">
        <p>@Model.Description</p>
    </div>
    <div class="modal-footer">
        <div class="row">
            <div class="col-sm-6">
                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>

                @Ajax.ActionLink("Edit", "Edit", "Visits",
                new { Id = Model.Id },
                new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "vns-modal-content" },
                new { @class = "btn btn-warning btn-sm", data_target = "#vns-visit-modal" })
            </div>
            <div class="col-sm-6">
                <p class="edit-info">
                    Added: @Html.DisplayFor(v => Model.CreatedOn)<br />
                    Edited: @Html.DisplayFor(v => Model.LastModifiedOn)
                </p>
            </div>
        </div>
    </div>
</div>

VNS.Web/Views/Visits/_VisitEditPartial.cshtml
@using VNS.Web.Models.Visits
@model VisitDetailsViewModel

<div class="panel panel-warning">
    <div class="panel-heading">
        @*<button type="button" class="btn btn-warning btn-sm btn-circle">
                <i class="fa fa-pencil"></i>
            </button>*@
        <img src="~/Content/images/girl-01.svg" class="profile-image pull-right" alt="profile-image" />
        <h4>@Model.NurseName</h4>
        <p>@Model.Date.ToString("dd.MM.yy")</p>
    </div>
    
    @using (Ajax.BeginForm("Edit", "Visits",
        new AjaxOptions
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
            // TODO: Find a better way to notify
            OnSuccess = "alert('Updated successfully')",
            UpdateTargetId = "vns-modal-content"
        },
        new { @class = "small" }))
    {
        @*@Html.AntiForgeryToken()*@

        <div class="panel-body">

            <p>Edit form</p>

            <fieldset>
                @Html.HiddenFor(v => v.Id)

                <div class="form-group">
                    @Html.LabelFor(v => v.Date, new { @class = "control-label" })
                    @Html.EditorFor(v => v.Date, new { htmlAttributes = new { @class = "form-control input-sm" } })
                    @Html.ValidationMessageFor(v => v.Date)
                </div>
                <div class="form-group">
                    @Html.LabelFor(v => v.NurseName, new { @class = "control-label" })
                    @Html.EditorFor(v => v.NurseName, new { htmlAttributes = new { @class = "form-control input-sm", @readonly = "true" } })
                </div>
                <div class="form-group">
                    @Html.LabelFor(v => v.Description, new { @class = "control-label" })
                    @Html.EditorFor(v => v.Description, new { htmlAttributes = new { @class = "form-control input-sm" } })
                    @Html.ValidationMessageFor(v => v.Description, "", new { @class = "text-danger" })
                </div>
            </fieldset>
        </div>

        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-6">
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-warning btn-sm">Save</button>
                </div>
                <div class="col-sm-6">
                    <p class="edit-info">
                        Added: @Html.DisplayFor(v => Model.CreatedOn)<br />
                        @Html.HiddenFor(v => Model.CreatedOn)
                        Edited: @Html.DisplayFor(v => Model.LastModifiedOn)
                        @Html.HiddenFor(v => Model.LastModifiedOn)
                    </p>
                </div>
            </div>
        </div>
    }
</div>

VNS.Web/Views/Visits/_VisitsListPartial.cshtml
@using VNS.Web.Models.Visits
@model VisitsViewModel

@if (Model.Visits.Count() > 0)
{
    <div class="row text-center">
        @Html.Partial("_PaginationPartial", Model.PageCount)
    </div>

    <div class="row vns-valign">
        @foreach (var visit in Model.Visits)
        {
            @Html.Partial("_VisitCardPartial", visit)
        }
    </div>

    <div class="row text-center">
        @Html.Partial("_PaginationPartial", Model.PageCount)
    </div>
}
else
{
    <p class="text-center">No visits to show</p>
}